import type { SwarmEvent } from "@/lib/execution/swarm-event-stream";

export type QuickUseType = "computer-use" | "agent-swarm" | "deep-research";
export type QuickUseResultType =
  | "comparison"
  | "research"
  | "price_list"
  | "single_fact"
  | "list"
  | "general";

export interface QuickUseCreditInfo {
  estimatedCredits?: number;
  creditsUsed?: number;
  creditsRemaining?: number;
}

export interface QuickUseArtifact {
  kind: "image" | "link" | "file";
  name: string;
  url?: string;
  dataUrl?: string;
  mimeType?: string;
}

export interface QuickUseSource {
  id?: number;
  title: string;
  url: string;
  domain?: string;
  snippet?: string;
}

/* ── File Upload Types ── */

export const ALLOWED_UPLOAD_TYPES = [
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "text/csv",
  "text/plain",
  "application/json",
  "image/png",
  "image/jpeg",
  "image/webp",
] as const;

export const ALLOWED_EXTENSIONS = [
  ".pdf", ".docx", ".xlsx", ".csv", ".txt", ".json", ".png", ".jpg", ".jpeg", ".webp",
] as const;

export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB
export const MAX_FILES_PER_MESSAGE = 5;

export interface QuickUseFileAttachment {
  /** Unique ID for this attachment */
  id: string;
  /** Original file name */
  fileName: string;
  /** MIME type */
  mimeType: string;
  /** File size in bytes */
  size: number;
  /** Supabase Storage path (server-side reference) */
  storagePath: string;
  /** Signed download URL (temporary) */
  url: string;
}

/** A file generated by the AI as output */
export interface QuickUseGeneratedFile {
  /** File type indicator */
  kind: "xlsx" | "pdf" | "docx" | "csv";
  /** Display name */
  name: string;
  /** Download URL (Supabase Storage, expires after 7 days) */
  url: string;
  /** File size in bytes */
  size: number;
  /** MIME type */
  mimeType: string;
}

export interface QuickUseResult {
  title?: string;
  summary: string;
  markdown?: string;
  resultType?: QuickUseResultType;
  followUpQuestions?: string[];
  model?: string;
  durationMs?: number;
  data?: unknown;
  artifacts?: QuickUseArtifact[];
  sources?: QuickUseSource[];
  generatedFiles?: QuickUseGeneratedFile[];
  qualityScore?: number;
  meta?: Record<string, unknown>;
}

export type QuickUseStreamEvent =
  | {
      type: "meta";
      meta: {
        estimatedCredits?: number;
        executionId?: string;
      };
    }
  | {
      type: "progress";
      message: string;
      detail?: string;
    }
  | {
      type: "finding";
      message: string;
    }
  | {
      type: "swarm_event";
      event: SwarmEvent;
    }
  | {
      type: "result";
      result: QuickUseResult;
      credits?: QuickUseCreditInfo;
    }
  | {
      type: "error";
      error: string;
      suggestions?: string[];
    };
