import type { SwarmEvent } from "@/lib/execution/swarm-event-stream";

export type QuickUseType = "computer-use" | "agent-swarm" | "deep-research";
export type QuickUseResultType =
  | "comparison"
  | "research"
  | "instant_extract"
  | "price_list"
  | "single_fact"
  | "list"
  | "general";

export interface QuickUseCreditInfo {
  estimatedCredits?: number;
  creditsUsed?: number;
  creditsRemaining?: number;
}

export interface QuickUseArtifact {
  kind: "image" | "link" | "file";
  name: string;
  url?: string;
  dataUrl?: string;
  mimeType?: string;
}

export interface QuickUseSource {
  id?: number;
  title: string;
  url: string;
  domain?: string;
  snippet?: string;
}

/* ── File Upload Types ── */

export const ALLOWED_UPLOAD_TYPES = [
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "text/csv",
  "text/plain",
  "application/json",
  "image/png",
  "image/jpeg",
  "image/webp",
] as const;

export const ALLOWED_EXTENSIONS = [
  ".pdf", ".docx", ".xlsx", ".csv", ".txt", ".json", ".png", ".jpg", ".jpeg", ".webp",
] as const;

export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB
export const MAX_FILES_PER_MESSAGE = 5;

export interface QuickUseFileAttachment {
  /** Unique ID for this attachment */
  id: string;
  /** Original file name */
  fileName: string;
  /** MIME type */
  mimeType: string;
  /** File size in bytes */
  size: number;
  /** Supabase Storage path (server-side reference) */
  storagePath: string;
  /** Signed download URL (temporary) */
  url: string;
}

/** A file generated by the AI as output */
export interface QuickUseGeneratedFile {
  /** File type indicator */
  kind: "xlsx" | "pdf" | "docx" | "csv";
  /** Display name */
  name: string;
  /** Download URL (Supabase Storage, expires after 7 days) */
  url: string;
  /** File size in bytes */
  size: number;
  /** MIME type */
  mimeType: string;
}

export interface QuickUseResult {
  title?: string;
  summary: string;
  markdown?: string;
  resultType?: QuickUseResultType;
  followUpQuestions?: string[];
  model?: string;
  durationMs?: number;
  data?: unknown;
  artifacts?: QuickUseArtifact[];
  sources?: QuickUseSource[];
  generatedFiles?: QuickUseGeneratedFile[];
  qualityScore?: number;
  meta?: Record<string, unknown>;
}

/* ── Background Task Types ── */

export type QuickUseTaskStatus = "RUNNING" | "PAUSED" | "COMPLETED" | "FAILED" | "CANCELLED";

export type InterventionType = "redirect" | "add_context" | "pause" | "resume" | "cancel";

export interface QuickUseIntervention {
  id: string;
  type: InterventionType;
  message: string;
  timestamp: string;
}

export interface QuickUseTaskSummary {
  id: string;
  type: QuickUseType;
  status: QuickUseTaskStatus;
  inputPreview: string;
  creditsUsed: number;
  createdAt: string;
  completedAt: string | null;
  hasResult: boolean;
}

export interface QuickUseTaskDetail extends QuickUseTaskSummary {
  input: { message: string; files?: QuickUseFileAttachment[] };
  config: Record<string, unknown> | null;
  progress: {
    currentStep?: string;
    agentStatuses?: Record<string, { id: string; task: string; status: string; detail?: string }>;
    findings?: string[];
  } | null;
  result: QuickUseResult | null;
  credits: QuickUseCreditInfo | null;
  interventions: QuickUseIntervention[];
  error: string | null;
}

export interface QuickUseMemoryPreview {
  id: string;
  taskId: string;
  type: QuickUseType;
  title?: string;
  summary: string;
  ageLabel: string;
  createdAt: string;
  highlights?: string[];
  sourceDomains?: string[];
  fileNames?: string[];
}

/* ── Stream Events ── */

/* ── Live Browser View Types ── */

export interface LiveBrowserStep {
  stepIndex: number;
  action: string;
  actionDetail: string;
  url: string;
  success?: boolean;
  durationMs?: number;
}

export type QuickUseStreamEvent =
  | {
      type: "meta";
      meta: {
        estimatedCredits?: number;
        executionId?: string;
        taskId?: string;
      };
    }
  | {
      type: "progress";
      message: string;
      detail?: string;
    }
  | {
      type: "finding";
      message: string;
    }
  | {
      type: "swarm_event";
      event: SwarmEvent;
    }
  | {
      type: "memory";
      memories: QuickUseMemoryPreview[];
      autoApplied?: boolean;
    }
  | {
      type: "result";
      result: QuickUseResult;
      credits?: QuickUseCreditInfo;
    }
  | {
      type: "error";
      error: string;
      suggestions?: string[];
    }
  | {
      type: "intervention_ack";
      interventionId: string;
      message: string;
    }
  | {
      /** Browser navigated to a new URL */
      type: "browser_navigation";
      url: string;
      stepIndex: number;
    }
  | {
      /** Live screenshot from browser (JPEG, max ~100KB) */
      type: "browser_screenshot";
      /** Base64 JPEG data (no data URL prefix) */
      imageData: string;
      stepIndex: number;
      url: string;
    }
  | {
      /** Agent performed an action */
      type: "browser_action";
      step: LiveBrowserStep;
    }
  | {
      /** Agent's current reasoning/thinking */
      type: "browser_thinking";
      thought: string;
      stepIndex: number;
    }
  | {
      /** A step completed */
      type: "browser_step_complete";
      stepIndex: number;
      action: string;
      success: boolean;
    };
